// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
  account_id,
  type,
  amount_cents,
  balance_after_cents
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, account_id, type, amount_cents, balance_after_cents, related_account_id, reference, created_at
`

type CreateTransactionParams struct {
	AccountID         int64
	Type              TransactionType
	AmountCents       int64
	BalanceAfterCents int64
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.AccountID,
		arg.Type,
		arg.AmountCents,
		arg.BalanceAfterCents,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.AmountCents,
		&i.BalanceAfterCents,
		&i.RelatedAccountID,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, account_id, type, amount_cents, balance_after_cents, related_account_id, reference, created_at FROM transactions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransaction(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.AmountCents,
		&i.BalanceAfterCents,
		&i.RelatedAccountID,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, account_id, type, amount_cents, balance_after_cents, related_account_id, reference, created_at FROM transactions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2
OFFSET $3
`

type ListTransactionsParams struct {
	AccountID int64
	Limit     int32
	Offset    int32
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.AmountCents,
			&i.BalanceAfterCents,
			&i.RelatedAccountID,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
